<?php
require_once('vendor/autoload.php');
require_once('functions/enqueue.php');
require_once('functions/theme-support.php');
require_once('functions/customize.php');
require_once('functions/acf-fields.php');
require_once('functions/custom-post-types.php');
require_once('functions/custom-taxonomies.php');
require_once('functions/load-category.php');
require_once('functions/load-more.php');
